# arxivの学問領域の指定
subject: 'cs'

# 検索キーワード
keywords:
        kaggle: 1
        reinforce: 1
        click: 1
        bandit: 1
        adscience: 1
        optimization: 1
        real time bidding: 3
        clustering: 1
